<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePropertiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('properties', function (Blueprint $table) {
            $table->id();
            $table->char('ref_id',36);
            $table->string('ref_resource');
            $table->char('salesforce_id',36);
            $table->timestamp('last_sync_modify',0);
            $table->unsignedBigInteger('last_property_price_history_id');
            $table->unsignedBigInteger('property_feature_id');
            $table->unsignedBigInteger('listing_id');
            $table->unsignedBigInteger('contact_id');
            $table->unsignedBigInteger('owner_id');
            $table->unsignedBigInteger('account_id');
            $table->string('project_building');
            $table->text('name');
            $table->double('sale_price_asking',18,2);
            $table->double('sale_asking_price_per_sqm',18,2);
            $table->timestamp('sale_price_asking_date',0);
            $table->unsignedBigInteger('sale_price_asking_updated_by');
            $table->double('sale_price',18,2);
            $table->double('sale_price_per_sqm',18,2);
            $table->timestamp('sale_price_date',0);
            $table->unsignedBigInteger('sale_price_updated_by');
            $table->double('sale_list_price',18,2);
            $table->double('sale_list_price_per_sqm',18,2);
            $table->timestamp('sale_list_price_date',0);
            $table->unsignedBigInteger('sale_list_price_updated_by');
            $table->double('sold_price',18,2);
            $table->double('sold_price_per_sqm',18,2);
            $table->timestamp('sold_price_date',0);
            $table->unsignedBigInteger('sold_price_updated_by');
            $table->double('rent_price_asking',18,2);
            $table->double('rent_asking_price_per_sqm',18,2);
            $table->timestamp('rent_price_asking_date',0);
            $table->unsignedBigInteger('rent_price_asking_updated_by');
            $table->double('rent_price',18,2);
            $table->double('rent_price_per_sqm',18,2);
            $table->timestamp('rent_price_date',0);
            $table->unsignedBigInteger('rent_price_updated_by');
            $table->double('rent_list_price',18,2);
            $table->double('rent_list_price_per_sqm',18,2);
            $table->timestamp('rent_list_price_date',0);
            $table->unsignedBigInteger('rent_list_price_updated_by');
            $table->double('rented_price',18,2);
            $table->double('rented_price_per_sqm',18,2);
            $table->timestamp('rented_price_date',0);
            $table->unsignedBigInteger('rented_price_updated_by');
            $table->string('street_no');
            $table->string('house_no');
            $table->string('address');
            $table->string('full_address');
            $table->string('zip_postalcode');
            $table->string('latitude');
            $table->string('longitude');
            $table->dateTime('published_at',0);
            $table->unsignedBigInteger('published_by');
            $table->integer('unit_total_bedroom',0);
            $table->integer('unit_total_bathroom',0);
            $table->integer('unit_total_livingroom',0);
            $table->integer('unit_total_floor',0);
            $table->integer('unit_total_parking',0);
            $table->integer('unit_total_car_parking',0);
            $table->integer('unit_total_motor_parking',0);
            $table->integer('unit_total_diningroom',0);
            $table->integer('unit_total_doors',0);
            $table->double('land_width',18,2);
            $table->double('land_length',18,2);
            $table->double('land_area',18,2);
            $table->double('land_area_by_title_deed',18,2);
            $table->string('title_deed_no');
            $table->string('parcel_no');
            $table->double('issued_year',0,0);
            $table->longText('description');
            $table->text('note');
            $table->string('location_grade');
            $table->string('title_deed_type');
            $table->string('record_type');
            $table->string('data_source');
            $table->string('zone_type');
            $table->string('land_shape_type');
            $table->string('facing_type');
            $table->string('tenure_type');
            $table->string('label_type');
            $table->string('type');
            $table->unsignedBigInteger('created_by');
            $table->unsignedBigInteger('updated_by');
            $table->timestamp('created_at',0);
            $table->timestamp('updated_at',0);
            $table->timestamp('deleted_at',0);
            $table->double('building_width',18,2);
            $table->double('building_length',18,2);
            $table->double('building_height',18,2);
            $table->double('building_area',18,2);
            $table->text('image');
            $table->text('image_left_side');
            $table->text('image_right_side');
            $table->text('image_back_side');
            $table->text('image_opposite');
            $table->text('gallery');
            $table->text('land_document');
            $table->text('title_deed_photos');
            $table->integer('stories',0);
            $table->tinyInteger('is_rent');
            $table->tinyInteger('is_sale');
            $table->tinyInteger('is_appraisal');
            $table->double('indication_min_price',0,0);
            $table->dateTime('indication_price_date',0);
            $table->unsignedBigInteger('indication_price_updated_by');
            $table->double('indication_max_price',0,0);
            $table->string('prefix');
            $table->string('sale_commission');
            $table->string('rental_cmmission');
            $table->string('exclusive_listing');
            $table->string('shape');
            $table->string('current_use');
            $table->string('topography');
            $table->string('functional_utilities');
            $table->string('main_street');
            $table->double('price_per_sqm',0,0);
            $table->unsignedBigInteger('manager_id');
            $table->text('video_embadded');
            $table->json('surrounding');
            $table->string('propery_code');
            $table->string('code');
            $table->string('status');
            $table->double('rating',0,0);
            $table->string('agreement_type');
            $table->text('agreement_file');
            $table->date('agreement_sign_date');
            $table->date('agreement_expired_date');
            $table->json('polygon');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('properties');
    }
}
